/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exammanagementsystemf;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
/**
 *
 * @author ANTON
 */
public class adminUserManagement extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(adminUserManagement.class.getName());

    /**
     * Creates new form adminUserManagement
     */
    public adminUserManagement() {
        initComponents();
        try {
            Connection();
        } catch (SQLException ex) {
            System.getLogger(adminUserManagement.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        setLocationRelativeTo(null);
        
    }
    Connection con;
    Statement st;
    PreparedStatement pst;
    
    public static final String DbName = "exammanagementsystem";
    private static final String DbDriver = "com.mysql.cj.jdbc.Driver";
    private static final String DbUrl = "jdbc:mysql://localhost:3306/"+DbName;
    private static final String DbUsername = "root";
    private static final String DbPassword = "";
    
    public void Connection() throws SQLException{
        try {
            Class.forName(DbDriver);
            con = DriverManager.getConnection(DbUrl, DbUsername, DbPassword);
            st = con.createStatement();
            if(con !=null){
                System.out.println("Connection Successful");
            }
        } catch (ClassNotFoundException ex) {
            System.getLogger(register.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAddStudentId = new javax.swing.JTextField();
        txtAddSection = new javax.swing.JTextField();
        txtAddPassword = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAddUsername = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnAdminUMLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnAdminUMDashboard = new javax.swing.JButton();
        btnAdminUMUserManagement = new javax.swing.JButton();
        btnAdminUMExams = new javax.swing.JButton();
        btnAdminUMResults = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(207, 213, 223));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(225, 232, 245));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Student Information");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTable1.setBackground(new java.awt.Color(160, 175, 200));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student ID", "Username", "Section"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 630, 200));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 670, 250));

        jPanel4.setBackground(new java.awt.Color(235, 239, 248));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Add Student");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Student ID:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Username:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Section:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        txtAddStudentId.setBackground(new java.awt.Color(140, 155, 180));
        txtAddStudentId.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(txtAddStudentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 230, -1));

        txtAddSection.setBackground(new java.awt.Color(140, 155, 180));
        txtAddSection.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(txtAddSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 230, -1));

        txtAddPassword.setBackground(new java.awt.Color(140, 155, 180));
        txtAddPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(txtAddPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 230, -1));

        jButton2.setBackground(new java.awt.Color(120, 135, 165));
        jButton2.setText("Save");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 70, -1));

        jButton3.setBackground(new java.awt.Color(120, 135, 165));
        jButton3.setText("Edit");
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 170, 70, -1));

        jButton4.setBackground(new java.awt.Color(120, 135, 165));
        jButton4.setText("Delete");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 70, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\book-open-reader.png")); // NOI18N
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 120, 140));

        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Password:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        txtAddUsername.setBackground(new java.awt.Color(140, 155, 180));
        txtAddUsername.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(txtAddUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 230, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 670, 210));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 710, 500));

        jPanel1.setBackground(new java.awt.Color(71, 85, 105));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdminUMLogout.setText("Logout");
        jPanel1.add(btnAdminUMLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 170, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\ExamMSystem.Images\\admin.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Admin");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jButton1.setBackground(new java.awt.Color(30, 41, 59));
        jButton1.setText("Logout");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 170, 30));

        btnAdminUMDashboard.setBackground(new java.awt.Color(30, 41, 59));
        btnAdminUMDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminUMDashboard.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\dashboard-panel.png")); // NOI18N
        btnAdminUMDashboard.setText("Dashboard");
        btnAdminUMDashboard.addActionListener(this::btnAdminUMDashboardActionPerformed);
        jPanel1.add(btnAdminUMDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 170, 50));

        btnAdminUMUserManagement.setBackground(new java.awt.Color(30, 41, 59));
        btnAdminUMUserManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminUMUserManagement.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\user-gear.png")); // NOI18N
        btnAdminUMUserManagement.setText("User Management");
        jPanel1.add(btnAdminUMUserManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 170, 50));

        btnAdminUMExams.setBackground(new java.awt.Color(30, 41, 59));
        btnAdminUMExams.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminUMExams.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\test.png")); // NOI18N
        btnAdminUMExams.setText("Exams");
        btnAdminUMExams.addActionListener(this::btnAdminUMExamsActionPerformed);
        jPanel1.add(btnAdminUMExams, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 170, 50));

        btnAdminUMResults.setBackground(new java.awt.Color(30, 41, 59));
        btnAdminUMResults.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminUMResults.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\chart-simple-horizontal.png")); // NOI18N
        btnAdminUMResults.setText("Results");
        btnAdminUMResults.addActionListener(this::btnAdminUMResultsActionPerformed);
        jPanel1.add(btnAdminUMResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 170, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 210, 500));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\Download CURVE WAVE ABSTRACT BACKGROUND BLUE CYAN for free.jpg")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFrame jf = new JFrame();
        jf.setAlwaysOnTop(true);
        int a = JOptionPane.showConfirmDialog(jf, "Do you really want to logout?", "select", JOptionPane.YES_NO_OPTION);
        if (a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAdminUMDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminUMDashboardActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new adminDashboard().setVisible(true);
    }//GEN-LAST:event_btnAdminUMDashboardActionPerformed

    private void btnAdminUMExamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminUMExamsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new adminExams().setVisible(true);
    }//GEN-LAST:event_btnAdminUMExamsActionPerformed

    private void btnAdminUMResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminUMResultsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new adminResults().setVisible(true);
    }//GEN-LAST:event_btnAdminUMResultsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int studentId;
        String section, username, password;
        if("".equals(txtAddStudentId.getText())){
            JOptionPane.showMessageDialog(new JFrame(), "Required to add Student ID");
        }
        if("".equals(txtAddSection.getText())){
            JOptionPane.showMessageDialog(new JFrame(), "Required to Add Section");
        }
        if("".equals(txtAddUsername.getText())){
            JOptionPane.showMessageDialog(new JFrame(), "Required to add Username");
        }
        if("".equals(txtAddPassword.getText())){
            JOptionPane.showMessageDialog(new JFrame(), "Required to add Password");
        }else{
            studentId = Integer.parseInt(txtAddStudentId.getText());
            section = txtAddSection.getText();
            username = txtAddUsername.getText();
            password = txtAddPassword.getText();
            
            String queryAddStudent = "INSERT INTO accountStudents(student_id, section, username, password)"
                    + "VALUES ('" + studentId + "', '" + section +"', '" + username + "', '" + password + "')";
            try {
                st.execute(queryAddStudent);
            } catch (SQLException ex) {
                System.getLogger(adminUserManagement.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
            JOptionPane.showMessageDialog(new JFrame(), "Student added successfuly");
            
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new adminUserManagement().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminUMDashboard;
    private javax.swing.JButton btnAdminUMExams;
    private javax.swing.JButton btnAdminUMLogout;
    private javax.swing.JButton btnAdminUMResults;
    private javax.swing.JButton btnAdminUMUserManagement;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAddPassword;
    private javax.swing.JTextField txtAddSection;
    private javax.swing.JTextField txtAddStudentId;
    private javax.swing.JTextField txtAddUsername;
    // End of variables declaration//GEN-END:variables
}
